# Generated by Django 5.2.3 on 2025-06-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('disaster_type', models.CharField(choices=[('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Fire', 'Fire'), ('Hurricanes', 'Hurricanes'), ('Landslides', 'Landslides')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EarthquakeData',
            fields=[
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth', models.FloatField()),
                ('mag', models.FloatField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('place', models.TextField()),
            ],
            options={
                'db_table': 'earthquake_data',
            },
        ),
    ]
