# Generated by Django 5.2.3 on 2025-07-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandslideEvent',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('location_description', models.CharField(max_length=255)),
                ('location_accuracy', models.CharField(blank=True, max_length=100, null=True)),
                ('landslide_category', models.CharField(max_length=100)),
                ('landslide_trigger', models.CharField(max_length=100)),
                ('landslide_size', models.CharField(max_length=100)),
                ('fatality_count', models.IntegerField(blank=True, null=True)),
                ('injury_count', models.IntegerField(blank=True, null=True)),
                ('event_import_id', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('event_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='earthquakedata',
            name='depth',
        ),
        migrations.AddField(
            model_name='earthquakedata',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='earthquakedata',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
