# Generated by Django 5.2.3 on 2025-07-03 05:25
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
    ('disaster_data', '0002_landslideevent_remove_earthquakedata_depth_and_more'),
]

    operations = [
        migrations.RunSQL('SELECT 1;')
    ]
