# Generated by Django 5.2.3 on 2025-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_data', '0003_auto_20250703_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='HurricaneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50, null=True)),
                ('number', models.IntegerField(null=True)),
                ('basin', models.CharField(max_length=50, null=True)),
                ('subbasin', models.CharField(max_length=50, null=True)),
                ('iso_time', models.DateTimeField(null=True)),
                ('nature', models.CharField(max_length=50, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'hurricane_data',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='landslideevent',
            options={'managed': False},
        ),
    ]
