# Generated by Django 5.2.3 on 2025-07-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_data', '0004_hurricanedata_alter_landslideevent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterModelTable(
            name='landslideevent',
            table='disaster_landslide',
        ),
    ]
