# Generated by Django 5.2.4 on 2025-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_data', '0007_auto_20250727_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDisasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('table_name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='🌋', max_length=10)),
                ('color', models.CharField(default='#ff6600', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Landslide',
        ),
        migrations.AlterModelOptions(
            name='earthquakedata',
            options={'managed': False},
        ),
    ]
