# Generated by Django 5.2.4 on 2025-07-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_data', '0008_customdisastertype_delete_landslide_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDisasterType',
        ),
        migrations.AlterField(
            model_name='uploadeddataset',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
