# Generated by Django 5.2.4 on 2025-07-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_data', '0009_delete_customdisastertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDisasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(default='#007BFF', max_length=10)),
                ('table_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandslideYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
    ]
