# Generated by Django 5.2.4 on 2025-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_data', '0010_customdisastertype_landslideyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdisastertype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
